// client/app/(admin)/admin/sponsors/page.tsx
"use client";

import { useEffect, useState } from "react";
import { sponsorService } from "@/lib/services/sponsor.service";
import { Sponsor } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { toast } from "sonner";
import { Loader2, Plus, Trash2 } from "lucide-react";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";

export default function AdminSponsorsPage() {
    const [sponsors, setSponsors] = useState<Sponsor[]>([]);
    const [loading, setLoading] = useState(true);
    const [isDialogOpen, setIsDialogOpen] = useState(false);
    const [file, setFile] = useState<File | null>(null);
    const [name, setName] = useState("");

    useEffect(() => {
        loadSponsors();
    }, []);

    const loadSponsors = async () => {
        try {
            const res = await sponsorService.getSponsors();
            setSponsors(res.data);
        } catch (error) {
            toast.error("Failed to load sponsors");
        } finally {
            setLoading(false);
        }
    };

    const handleCreate = async () => {
        if (!file || !name) {
            toast.error("Name and Image are required");
            return;
        }

        try {
            const formData = new FormData();
            formData.append("name", name);
            formData.append("image", file);

            await sponsorService.createSponsor(formData);
            toast.success("Sponsor added");
            setIsDialogOpen(false);
            setName("");
            setFile(null);
            loadSponsors();
        } catch (error) {
            toast.error("Failed to add sponsor");
        }
    };

    const handleDelete = async (id: number) => {
        try {
            await sponsorService.deleteSponsor(id);
            toast.success("Sponsor deleted");
            loadSponsors();
        } catch (error) {
            toast.error("Failed to delete sponsor");
        }
    };

    if (loading) return <div className="flex justify-center p-8"><Loader2 className="animate-spin" /></div>;

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <h2 className="text-3xl font-bold tracking-tight">Sponsors</h2>
                <Button onClick={() => setIsDialogOpen(true)}>
                    <Plus className="mr-2 h-4 w-4" /> Add Sponsor
                </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-6">
                {sponsors.map((sponsor) => (
                    <Card key={sponsor.id}>
                        <div className="aspect-video w-full overflow-hidden bg-gray-100 flex items-center justify-center">
                            <img src={sponsor.imageUrl} alt={sponsor.name} className="object-cover h-full w-full" />
                        </div>
                        <CardHeader>
                            <CardTitle>{sponsor.name}</CardTitle>
                        </CardHeader>
                        <CardFooter>
                            <ConfirmDialog
                                title="Delete Sponsor"
                                description="Are you sure you want to delete this sponsor?"
                                onConfirm={() => handleDelete(sponsor.id)}
                            >
                                <Button variant="destructive" size="sm" className="w-full">
                                    <Trash2 className="w-4 h-4 mr-2" /> Delete
                                </Button>
                            </ConfirmDialog>
                        </CardFooter>
                    </Card>
                ))}
            </div>

            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Add New Sponsor</DialogTitle>
                    </DialogHeader>
                    <div className="space-y-4 py-4">
                        <div className="space-y-2">
                            <Label>Sponsor Name</Label>
                            <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Company Name" />
                        </div>
                        <div className="space-y-2">
                            <Label>Logo Image</Label>
                            <Input type="file" onChange={(e) => setFile(e.target.files?.[0] || null)} />
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" onClick={() => setIsDialogOpen(false)}>Cancel</Button>
                        <Button onClick={handleCreate}>Add Sponsor</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    );
}

// client/src/views/Sponsors/Sponsors.vue
<template>
    <AdminLayout>
        <PageBreadcrumb :pageTitle="currentPageTitle" />
        <div class="space-y-5 sm:space-y-6">
            <ComponentCard title="Sponsors Management">
                <div class="mb-4 flex justify-between items-center">
                    <h3 class="text-lg font-semibold text-gray-800 dark:text-white">All Sponsors</h3>
                    <button 
                        @click="goToAddSponsor"
                        class="px-4 py-2 bg-brand-500 text-white rounded-lg hover:bg-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2"
                    >
                        Add Sponsor
                    </button>
                </div>

                <!-- Loading State -->
                <div v-if="loading" class="flex justify-center items-center py-12">
                    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-brand-500"></div>
                </div>

                <!-- Data Table -->
                <DataTable 
                    v-else
                    :columns="columns"
                    :data="sponsors"
                    :showActions="true"
                    :onEdit="editSponsor"
                    :onDelete="deleteSponsor"
                >
                    <template #column-image="{ item }">
                        <div class="w-16 h-10 overflow-hidden rounded bg-gray-200 dark:bg-gray-700">
                            <img v-if="item.image" :src="item.image" alt="Sponsor" class="w-full h-full object-cover" />
                            <span v-else class="flex items-center justify-center w-full h-full text-xs text-gray-500">No Img</span>
                        </div>
                    </template>

                    <template #column-link="{ item }">
                        <a :href="item.link" target="_blank" class="text-brand-600 hover:underline truncate block max-w-xs">
                            {{ item.link }}
                        </a>
                    </template>

                    <template #column-isActive="{ item }">
                        <span :class="item.isActive ? 'text-green-600' : 'text-gray-500'">
                            {{ item.isActive ? 'Active' : 'Inactive' }}
                        </span>
                    </template>
                </DataTable>
            </ComponentCard>
        </div>
    </AdminLayout>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useRouter } from "vue-router";
import { SponsorsAPI } from "@/api/SponsorsAPI";
import PageBreadcrumb from "@/components/common/PageBreadcrumb.vue";
import AdminLayout from "@/components/layout/AdminLayout.vue";
import ComponentCard from "@/components/common/ComponentCard.vue";
import DataTable, { type Column } from "@/components/DataTable.vue";

const router = useRouter();
const currentPageTitle = ref("Sponsors");
const sponsors = ref([]);
const loading = ref(false);

const columns: Column[] = [
    { key: 'id', title: 'ID', type: 'text' },
    { key: 'image', title: 'Logo', type: 'custom' },
    { key: 'name', title: 'Name', type: 'text' },
    { key: 'link', title: 'Website', type: 'custom' },
    { key: 'isActive', title: 'Status', type: 'custom' },
];

const fetchSponsors = async () => {
    loading.value = true;
    try {
        const response = await SponsorsAPI.getAllSponsors({});
        sponsors.value = response.data.data || response.data;
    } catch (error) {
        console.error('Error fetching sponsors:', error);
    } finally {
        loading.value = false;
    }
};

const goToAddSponsor = () => {
    router.push('/sponsors/add');
};

const editSponsor = (item: any) => {
    router.push(`/sponsors/edit/${item.id}`);
};

const deleteSponsor = async (item: any) => {
    if (confirm('Are you sure you want to delete this sponsor?')) {
        try {
            await SponsorsAPI.deleteSponsor(item.id);
            fetchSponsors();
        } catch (error) {
            console.error('Error deleting sponsor:', error);
            alert('Failed to delete sponsor');
        }
    }
};

onMounted(() => {
    fetchSponsors();
});
</script>
