// client/app/(admin)/admin/sports/page.tsx
"use client";

import { useEffect, useState } from "react";
import { sportService } from "@/lib/services/sport.service";
import { Sport } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { toast } from "sonner";
import { Loader2, Trash2, Plus } from "lucide-react";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";

export default function AdminSportsPage() {
  const [sports, setSports] = useState<Sport[]>([]);
  const [loading, setLoading] = useState(true);
  const [newSportName, setNewSportName] = useState("");

  useEffect(() => {
    loadSports();
  }, []);

  const loadSports = async () => {
    try {
      const res = await sportService.getSports();
      setSports(res.data);
    } catch {
      toast.error("Failed to load sports");
    } finally {
      setLoading(false);
    }
  };

  const handleCreate = async () => {
    if (!newSportName) return;
    try {
      await sportService.createSport({ name: newSportName });
      toast.success("Sport added");
      setNewSportName("");
      loadSports();
    } catch {
      toast.error("Failed to add sport");
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await sportService.deleteSport(id);
      toast.success("Sport deleted");
      loadSports();
    } catch {
      toast.error("Failed to delete sport");
    }
  };

  if (loading)
    return (
      <div className="flex justify-center p-8">
        <Loader2 className="animate-spin" />
      </div>
    );

  return (
    <div className="space-y-6">
      <h2 className="text-3xl font-bold tracking-tight">Sports</h2>

      <div className="flex gap-4 items-end max-w-sm">
        <div className="w-full space-y-2">
          <Input
            placeholder="New Sport Name"
            value={newSportName}
            onChange={(e) => setNewSportName(e.target.value)}
          />
        </div>
        <Button onClick={handleCreate}>
          <Plus className="h-4 w-4" /> Add
        </Button>
      </div>

      <div className="rounded-md border bg-white dark:bg-gray-900 max-w-2xl">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Activity Name</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {sports.map((sport) => (
              <TableRow key={sport.id}>
                <TableCell className="font-medium">{sport.name}</TableCell>
                <TableCell className="text-right">
                  <ConfirmDialog
                    title="Delete Sport"
                    description="Are you sure you want to delete this sport?"
                    onConfirm={() => handleDelete(sport.id.toString())}
                  >
                    <Button
                      variant="ghost"
                      size="icon"
                      className="text-destructive"
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </ConfirmDialog>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}

// client/src/views/Sports/Sports.vue
<template>
    <AdminLayout>
        <PageBreadcrumb :pageTitle="currentPageTitle" />
        <div class="space-y-5 sm:space-y-6">
            <ComponentCard title="Sports Management">
                <div class="mb-4 flex justify-between items-center">
                    <h3 class="text-lg font-semibold text-gray-800 dark:text-white">All Sports</h3>
                    <button 
                        @click="goToAddSport"
                        class="px-4 py-2 bg-brand-500 text-white rounded-lg hover:bg-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2"
                    >
                        Add Sport
                    </button>
                </div>

                <!-- Loading State -->
                <div v-if="loading" class="flex justify-center items-center py-12">
                    <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-brand-500"></div>
                </div>

                <!-- Data Table -->
                <DataTable 
                    v-else
                    :columns="columns"
                    :data="sports"
                    :showActions="true"
                    :onEdit="editSport"
                    :onDelete="deleteSport"
                >
                    <template #column-icon="{ item }">
                        <div class="w-10 h-10 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700 flex items-center justify-center">
                            <img v-if="item.icon" :src="item.icon" alt="Sport Icon" class="w-full h-full object-cover" />
                            <span v-else class="text-xs text-gray-500">No Icon</span>
                        </div>
                    </template>
                </DataTable>
            </ComponentCard>
        </div>
    </AdminLayout>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useRouter } from "vue-router";
import { SportsAPI } from "@/api/SportsAPI";
import PageBreadcrumb from "@/components/common/PageBreadcrumb.vue";
import AdminLayout from "@/components/layout/AdminLayout.vue";
import ComponentCard from "@/components/common/ComponentCard.vue";
import DataTable, { type Column } from "@/components/DataTable.vue";

const router = useRouter();
const currentPageTitle = ref("Sports");
const sports = ref([]);
const loading = ref(false);

const columns: Column[] = [
    { key: 'id', title: 'ID', type: 'text' },
    { key: 'icon', title: 'Icon', type: 'custom' },
    { key: 'name', title: 'Name', type: 'text' },
    { key: 'description', title: 'Description', type: 'text' },
];

const fetchSports = async () => {
    loading.value = true;
    try {
        const response = await SportsAPI.getAllSports({});
        sports.value = response.data.data || response.data;
    } catch (error) {
        console.error('Error fetching sports:', error);
    } finally {
        loading.value = false;
    }
};

const goToAddSport = () => {
    router.push('/sports/add');
};

const editSport = (item: any) => {
    router.push(`/sports/edit/${item.id}`);
};

const deleteSport = async (item: any) => {
    if (confirm('Are you sure you want to delete this sport?')) {
        try {
            await SportsAPI.deleteSport(item.id);
            fetchSports();
        } catch (error) {
            console.error('Error deleting sport:', error);
            alert('Failed to delete sport');
        }
    }
};

onMounted(() => {
    fetchSports();
});
</script>
